/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bi_project;

import io.github.bonigarcia.wdm.WebDriverManager;

public class App {

    // TODO: make it

    public static void main(String[] args) {
        System.out.println("ra");
    }
}
